print('CALCULANDO A TABUADA\n')
num = int(input('Digite um número: '))
print(f'{num} vezes 1 = {num * 1}')
print(f'{num} vezes 2 = {num * 2}')
print(f'{num} vezes 3 = {num * 3}')
print(f'{num} vezes 4 = {num * 4}')
print(f'{num} vezes 5 = {num * 5}')
print(f'{num} vezes 6 = {num * 6}')
print(f'{num} vezes 7 = {num * 7}')
print(f'{num} vezes 8 = {num * 8}')
print(f'{num} vezes 9 = {num * 9}')
print(f'{num} vezes 10 = {num * 10}')
print('--------------------------------')
